# A first introduction about injection pipeline runs for git 'push' commands in GitHub
# have a look at 'GitHub Actions Runner Images': https://github.com/actions/runner-images/
name: CI for Taskolib

# Controls when the action will run. Here when we enter 'git push'
on:
  push:
    branches: [ main ]
    path-ignore:
      - README.md
      - .vscode
      - data
      - debian
      # TODO path to be ignored in future release: - @anchor_playground playground

  pull_request:
    branches: [ main ]
    path-ignore:
      - README.md
      - .vscode
      - data
      - debian
      # TODO path to be ignored in future release: - *anchor_playground
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-run-tests-on-ubuntu:
    uses: ./.github/workflows/build_and_run_tests.yml
    with:
      platform: ubuntu-latest
